import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "bn";

export const translations = {
  en: {
    // ── Nav ─────────────────────────────────────────────────────────────
    nav_tournaments: "Tournaments",
    nav_leaderboard: "Leaderboard",
    nav_schedule: "Schedule",
    nav_results: "Results",
    nav_prizes: "Prizes",
    nav_teams: "Teams",
    nav_support: "Support",
    nav_contact: "Contact",
    nav_signin: "Sign In",
    nav_register: "Register",
    nav_profile: "Profile",
    nav_admin: "Admin",

    // ── Bottom Nav ───────────────────────────────────────────────────────
    bn_home: "Home",
    bn_tournament: "Tournament",
    bn_wallet: "Wallet",
    bn_profile: "Profile",
    bn_create: "Create",
    bn_menu: "Menu",

    // ── Menu Drawer ──────────────────────────────────────────────────────
    menu_profile: "Profile",
    menu_profile_desc: "View & edit your profile",
    menu_wallet: "Wallet",
    menu_wallet_desc: "Manage your balance",
    menu_my_matches: "My Matches",
    menu_my_matches_desc: "Manage matches & requests",
    menu_tournaments: "My Tournaments",
    menu_tournaments_desc: "Your tournament history",
    menu_team: "My Team",
    menu_team_desc: "Manage your squad",
    menu_referral: "Referral",
    menu_referral_desc: "Invite friends, earn rewards",
    menu_leaderboard: "Leaderboard",
    menu_leaderboard_desc: "Global rankings",
    menu_support: "Support",
    menu_support_desc: "Get help from our team",
    menu_admin_panel: "Admin Panel",
    menu_admin_desc: "Manage platform",
    menu_sign_in: "Sign In",
    menu_sign_out: "Sign Out",

    // ── Login Page ──────────────────────────────────────────────────────
    login_title: "Sign In",
    login_subtitle: "Welcome back, champion",
    login_email: "Email Address",
    login_password: "Password",
    login_forgot: "Forgot password?",
    login_btn: "Sign In",
    login_signing_in: "Signing in…",
    login_no_account: "Don't have an account?",
    login_register_now: "Register now",
    login_admin: "Admin Login",
    login_security: "Security Check",

    // ── Signup ──────────────────────────────────────────────────────────
    signup_title: "Create Account",
    signup_subtitle: "Join the Free Fire tournament community",
    signup_email: "Email Address",
    signup_username: "Username",
    signup_password: "Password",
    signup_confirm: "Confirm Password",
    signup_btn: "Create Account",
    signup_have_account: "Already have an account?",
    signup_signin: "Sign in",
    req_letters: "Must contain letters (a–z)",
    req_numbers: "Must contain numbers (0–9)",
    req_match: "Passwords match",

    // ── Home Page ────────────────────────────────────────────────────────
    home_badge: "Bangladesh Free Fire Esports",
    home_hero_1: "Dominate",
    home_hero_2: "Free Fire",
    home_hero_3: "Tournaments",
    home_hero_desc: "Compete in elite tournaments, build your squad, and claim real prize pools. Join, register, and prove you are the best.",
    home_next_tournament: "Next Tournament Starts In",
    home_find_tournaments: "Find Tournaments",
    home_view_leaderboard: "View Leaderboard",
    home_scroll: "Scroll",
    home_featured: "Featured",
    home_tournaments: "Tournaments",
    home_view_all: "View All",
    home_no_tournaments: "No Tournaments Yet",
    home_no_tournaments_desc: "The admin will post upcoming tournaments soon. Check back later.",
    home_community: "Community",
    home_matches: "Matches",
    home_no_community: "No Community Matches Yet",
    home_no_community_desc: "Be the first to host a community match!",
    home_host_match: "Host a Match",
    home_top: "Top",
    home_players: "Players",
    home_full_leaderboard: "Full Leaderboard",
    home_loading_rankings: "Loading rankings...",
    home_no_rankings: "No Rankings Yet",
    home_no_rankings_desc: "Play a match to appear on the leaderboard.",
    home_latest: "Latest",
    home_announcements: "Announcements",
    home_how_it: "How It",
    home_works: "Works",
    home_step1_title: "Register",
    home_step1_desc: "Create your account and complete your Free Fire profile with your UID and nickname.",
    home_step2_title: "Join Tournament",
    home_step2_desc: "Browse available tournaments, pay the entry fee via BKash or Nagad, and register your team.",
    home_step3_title: "Get Room Details",
    home_step3_desc: "Once approved, receive the Room ID and password from the admin before match time.",
    home_step4_title: "Win Prizes",
    home_step4_desc: "Compete hard, rank high, and receive your prize money directly to your mobile wallet.",

    // ── Table Headers ────────────────────────────────────────────────────
    th_rank: "#",
    th_player: "Player",
    th_kills: "Kills",
    th_points: "Points",

    // ── Tournament Card ──────────────────────────────────────────────────
    tc_join: "Join Now",
    tc_view: "View Details",
    tc_results: "View Results",
    tc_entry: "Entry",
    tc_prize: "Prize Pool",
    tc_slots: "Slots",
    tc_free: "FREE",
    tc_per_kill: "/kill",
    tc_loading: "Loading results…",
    tc_no_results: "No results published yet.",
    tc_match: "Match",
    tc_rank: "Rank",
    tc_player: "Player",
    tc_kills: "Kills",
    tc_points: "Points",
    tc_full: "Full",
    tc_registered: "Registered",

    // ── Community Matches ────────────────────────────────────────────────
    cm_title: "Community Matches",
    cm_create: "Create Match",
    cm_no_matches: "No matches found",
    cm_no_matches_desc: "Be the first to create a community match!",
    cm_tab_all: "All",
    cm_tab_br: "BR",
    cm_tab_cs: "Clash Squad",
    cm_tab_solo: "Solo",
    cm_tab_lone_wolf: "Lone Wolf",
    cm_tab_free: "Free Match",
    cm_entry: "Entry",
    cm_prize: "Prize",
    cm_slots: "Slots",
    cm_live: "LIVE",
    cm_full: "FULL",
    cm_private: "Private",
    cm_ended: "Ended",
    cm_room_ready: "Room Ready",
    cm_request_sent: "Request Sent",
    cm_joined: "Joined ✓",
    cm_locked: "🔒 Locked",
    cm_join: "JOIN →",
    cm_join_live: "Join Live",
    cm_by: "by",
    cm_join_modal_title: "Join Match",
    cm_player_name: "Player Name",
    cm_ff_uid: "Free Fire UID",
    cm_password: "Match Password",
    cm_balance: "Wallet Balance",
    cm_submit_join: "Submit & Join",
    cm_cancel: "Cancel",
    cm_my_matches: "My Joined Matches",
    cm_public_matches: "Public Matches",
    cm_free_entry: "FREE",

    // ── Dashboard ────────────────────────────────────────────────────────
    dash_title: "Dashboard",
    dash_profile: "Profile",
    dash_tournaments: "My Tournaments",
    dash_team: "Team",
    dash_deposits: "Deposits",
    dash_withdrawals: "Withdrawals",
    dash_edit: "Edit Profile",
    dash_save: "Save",
    dash_cancel: "Cancel",
    dash_username: "Username",
    dash_display_name: "Display Name",
    dash_ff_uid: "Free Fire UID",
    dash_ff_nick: "Free Fire Nickname",
    dash_email: "Email",
    dash_no_tournaments: "No tournament registrations yet.",
    dash_no_team: "You have not joined a team yet.",
    dash_status_approved: "Approved",
    dash_status_rejected: "Rejected",
    dash_status_pending: "Pending",

    // ── Wallet ───────────────────────────────────────────────────────────
    wallet_title: "Wallet",
    wallet_balance: "Available Balance",
    wallet_deposit: "Deposit",
    wallet_withdraw: "Withdraw",
    wallet_history: "Transaction History",
    wallet_amount: "Amount",
    wallet_method: "Method",
    wallet_tx_id: "Transaction ID",
    wallet_account: "Account Number",
    wallet_submit: "Submit",
    wallet_close: "Close",
    wallet_all: "All",
    wallet_pending: "Pending",
    wallet_approved: "Approved",
    wallet_rejected: "Rejected",
    wallet_no_txs: "No transactions found.",
    wallet_total_deposit: "Total Deposited",
    wallet_total_withdraw: "Total Withdrawn",
    wallet_entry_fees: "Entry Fees",
    wallet_prizes: "Prize Winnings",

    // ── Common ───────────────────────────────────────────────────────────
    loading: "Loading…",
    error: "Error",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    refresh: "Refresh",
    retry: "Retry",
    submit: "Submit",
    by: "By",
    free: "FREE",
    security_check: "Security Check",
    your_answer: "Your answer",
  },

  bn: {
    // ── Nav ─────────────────────────────────────────────────────────────
    nav_tournaments: "টুর্নামেন্ট",
    nav_leaderboard: "লিডারবোর্ড",
    nav_schedule: "সময়সূচি",
    nav_results: "ফলাফল",
    nav_prizes: "পুরস্কার",
    nav_teams: "দল",
    nav_support: "সহায়তা",
    nav_contact: "যোগাযোগ",
    nav_signin: "লগ ইন",
    nav_register: "নিবন্ধন",
    nav_profile: "প্রোফাইল",
    nav_admin: "অ্যাডমিন",

    // ── Bottom Nav ───────────────────────────────────────────────────────
    bn_home: "হোম",
    bn_tournament: "টুর্নামেন্ট",
    bn_wallet: "ওয়ালেট",
    bn_profile: "প্রোফাইল",
    bn_create: "তৈরি করুন",
    bn_menu: "মেনু",

    // ── Menu Drawer ──────────────────────────────────────────────────────
    menu_profile: "প্রোফাইল",
    menu_profile_desc: "প্রোফাইল দেখুন ও সম্পাদনা করুন",
    menu_wallet: "ওয়ালেট",
    menu_wallet_desc: "ব্যালেন্স পরিচালনা করুন",
    menu_my_matches: "আমার ম্যাচ",
    menu_my_matches_desc: "ম্যাচ ও অনুরোধ পরিচালনা করুন",
    menu_tournaments: "আমার টুর্নামেন্ট",
    menu_tournaments_desc: "আপনার টুর্নামেন্ট ইতিহাস",
    menu_team: "আমার দল",
    menu_team_desc: "আপনার স্কোয়াড পরিচালনা করুন",
    menu_referral: "রেফারেল",
    menu_referral_desc: "বন্ধুদের আমন্ত্রণ জানান, পুরস্কার পান",
    menu_leaderboard: "লিডারবোর্ড",
    menu_leaderboard_desc: "বৈশ্বিক র‍্যাঙ্কিং",
    menu_support: "সহায়তা",
    menu_support_desc: "আমাদের টিম থেকে সাহায্য নিন",
    menu_admin_panel: "অ্যাডমিন প্যানেল",
    menu_admin_desc: "প্ল্যাটফর্ম পরিচালনা করুন",
    menu_sign_in: "লগ ইন",
    menu_sign_out: "সাইন আউট",

    // ── Login Page ──────────────────────────────────────────────────────
    login_title: "লগ ইন",
    login_subtitle: "স্বাগতম, চ্যাম্পিয়ন",
    login_email: "ইমেইল ঠিকানা",
    login_password: "পাসওয়ার্ড",
    login_forgot: "পাসওয়ার্ড ভুলে গেছেন?",
    login_btn: "লগ ইন করুন",
    login_signing_in: "লগ ইন হচ্ছে…",
    login_no_account: "অ্যাকাউন্ট নেই?",
    login_register_now: "এখনই নিবন্ধন করুন",
    login_admin: "অ্যাডমিন লগিন",
    login_security: "নিরাপত্তা যাচাই",

    // ── Signup ──────────────────────────────────────────────────────────
    signup_title: "অ্যাকাউন্ট তৈরি করুন",
    signup_subtitle: "ফ্রি ফায়ার টুর্নামেন্ট কমিউনিটিতে যোগ দিন",
    signup_email: "ইমেইল ঠিকানা",
    signup_username: "ইউজারনেম",
    signup_password: "পাসওয়ার্ড",
    signup_confirm: "পাসওয়ার্ড নিশ্চিত করুন",
    signup_btn: "অ্যাকাউন্ট তৈরি করুন",
    signup_have_account: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    signup_signin: "লগ ইন করুন",
    req_letters: "অক্ষর থাকতে হবে (a–z)",
    req_numbers: "সংখ্যা থাকতে হবে (0–9)",
    req_match: "পাসওয়ার্ড মিলছে",

    // ── Home Page ────────────────────────────────────────────────────────
    home_badge: "বাংলাদেশ ফ্রি ফায়ার ই-স্পোর্টস",
    home_hero_1: "আধিপত্য বিস্তার করুন",
    home_hero_2: "ফ্রি ফায়ার",
    home_hero_3: "টুর্নামেন্টে",
    home_hero_desc: "এলিট টুর্নামেন্টে প্রতিযোগিতা করুন, স্কোয়াড গড়ুন এবং আসল পুরস্কার জিতুন। যোগ দিন এবং প্রমাণ করুন আপনি সেরা।",
    home_next_tournament: "পরবর্তী টুর্নামেন্ট শুরু হবে",
    home_find_tournaments: "টুর্নামেন্ট খুঁজুন",
    home_view_leaderboard: "লিডারবোর্ড দেখুন",
    home_scroll: "স্ক্রোল",
    home_featured: "বৈশিষ্ট্যযুক্ত",
    home_tournaments: "টুর্নামেন্ট",
    home_view_all: "সব দেখুন",
    home_no_tournaments: "এখনো কোনো টুর্নামেন্ট নেই",
    home_no_tournaments_desc: "অ্যাডমিন শীঘ্রই টুর্নামেন্ট পোস্ট করবেন। পরে আবার দেখুন।",
    home_community: "কমিউনিটি",
    home_matches: "ম্যাচ",
    home_no_community: "এখনো কোনো কমিউনিটি ম্যাচ নেই",
    home_no_community_desc: "প্রথম কমিউনিটি ম্যাচ হোস্ট করুন!",
    home_host_match: "ম্যাচ হোস্ট করুন",
    home_top: "শীর্ষ",
    home_players: "খেলোয়াড়",
    home_full_leaderboard: "সম্পূর্ণ লিডারবোর্ড",
    home_loading_rankings: "র‍্যাঙ্কিং লোড হচ্ছে...",
    home_no_rankings: "এখনো কোনো র‍্যাঙ্কিং নেই",
    home_no_rankings_desc: "লিডারবোর্ডে আসতে একটি ম্যাচ খেলুন।",
    home_latest: "সর্বশেষ",
    home_announcements: "ঘোষণা",
    home_how_it: "এটি কিভাবে",
    home_works: "কাজ করে",
    home_step1_title: "নিবন্ধন করুন",
    home_step1_desc: "আপনার অ্যাকাউন্ট তৈরি করুন এবং আপনার UID ও নিকনেম দিয়ে ফ্রি ফায়ার প্রোফাইল সম্পন্ন করুন।",
    home_step2_title: "টুর্নামেন্টে যোগ দিন",
    home_step2_desc: "উপলব্ধ টুর্নামেন্ট ব্রাউজ করুন, বিকাশ বা নগদের মাধ্যমে এন্ট্রি ফি দিন এবং দল নিবন্ধন করুন।",
    home_step3_title: "রুম বিবরণ পান",
    home_step3_desc: "অনুমোদনের পরে, ম্যাচের আগে অ্যাডমিনের কাছ থেকে রুম আইডি এবং পাসওয়ার্ড পান।",
    home_step4_title: "পুরস্কার জিতুন",
    home_step4_desc: "কঠোর প্রতিযোগিতা করুন, উচ্চ র‍্যাঙ্ক করুন এবং সরাসরি মোবাইল ওয়ালেটে পুরস্কার পান।",

    // ── Table Headers ────────────────────────────────────────────────────
    th_rank: "#",
    th_player: "খেলোয়াড়",
    th_kills: "কিল",
    th_points: "পয়েন্ট",

    // ── Tournament Card ──────────────────────────────────────────────────
    tc_join: "যোগ দিন",
    tc_view: "বিস্তারিত দেখুন",
    tc_results: "ফলাফল দেখুন",
    tc_entry: "প্রবেশ মূল্য",
    tc_prize: "পুরস্কার পুল",
    tc_slots: "আসন",
    tc_free: "বিনামূল্যে",
    tc_per_kill: "/কিল",
    tc_loading: "ফলাফল লোড হচ্ছে…",
    tc_no_results: "এখনো কোনো ফলাফল প্রকাশিত হয়নি।",
    tc_match: "ম্যাচ",
    tc_rank: "র‍্যাঙ্ক",
    tc_player: "খেলোয়াড়",
    tc_kills: "কিল",
    tc_points: "পয়েন্ট",
    tc_full: "পূর্ণ",
    tc_registered: "নিবন্ধিত",

    // ── Community Matches ────────────────────────────────────────────────
    cm_title: "কমিউনিটি ম্যাচ",
    cm_create: "ম্যাচ তৈরি করুন",
    cm_no_matches: "কোনো ম্যাচ পাওয়া যায়নি",
    cm_no_matches_desc: "প্রথম কমিউনিটি ম্যাচ তৈরি করুন!",
    cm_tab_all: "সকল",
    cm_tab_br: "BR",
    cm_tab_cs: "ক্ল্যাশ স্কোয়াড",
    cm_tab_solo: "সোলো",
    cm_tab_lone_wolf: "একা যোদ্ধা",
    cm_tab_free: "ফ্রি ম্যাচ",
    cm_entry: "প্রবেশ",
    cm_prize: "পুরস্কার",
    cm_slots: "আসন",
    cm_live: "লাইভ",
    cm_full: "পূর্ণ",
    cm_private: "প্রাইভেট",
    cm_ended: "শেষ",
    cm_room_ready: "রুম প্রস্তুত",
    cm_request_sent: "অনুরোধ পাঠানো হয়েছে",
    cm_joined: "যোগ দেওয়া হয়েছে ✓",
    cm_locked: "🔒 লক করা",
    cm_join: "যোগ দিন →",
    cm_join_live: "লাইভে যোগ দিন",
    cm_by: "দ্বারা",
    cm_join_modal_title: "ম্যাচে যোগ দিন",
    cm_player_name: "খেলোয়াড়ের নাম",
    cm_ff_uid: "ফ্রি ফায়ার UID",
    cm_password: "ম্যাচ পাসওয়ার্ড",
    cm_balance: "ওয়ালেট ব্যালেন্স",
    cm_submit_join: "জমা দিন ও যোগ দিন",
    cm_cancel: "বাতিল",
    cm_my_matches: "আমার যোগ দেওয়া ম্যাচ",
    cm_public_matches: "পাবলিক ম্যাচ",
    cm_free_entry: "বিনামূল্যে",

    // ── Dashboard ────────────────────────────────────────────────────────
    dash_title: "ড্যাশবোর্ড",
    dash_profile: "প্রোফাইল",
    dash_tournaments: "আমার টুর্নামেন্ট",
    dash_team: "দল",
    dash_deposits: "ডিপোজিট",
    dash_withdrawals: "উত্তোলন",
    dash_edit: "প্রোফাইল সম্পাদনা",
    dash_save: "সংরক্ষণ",
    dash_cancel: "বাতিল",
    dash_username: "ইউজারনেম",
    dash_display_name: "প্রদর্শন নাম",
    dash_ff_uid: "ফ্রি ফায়ার UID",
    dash_ff_nick: "ফ্রি ফায়ার নিকনেম",
    dash_email: "ইমেইল",
    dash_no_tournaments: "এখনো কোনো টুর্নামেন্ট নিবন্ধন নেই।",
    dash_no_team: "আপনি এখনো কোনো দলে যোগ দেননি।",
    dash_status_approved: "অনুমোদিত",
    dash_status_rejected: "প্রত্যাখ্যাত",
    dash_status_pending: "অপেক্ষমাণ",

    // ── Wallet ───────────────────────────────────────────────────────────
    wallet_title: "ওয়ালেট",
    wallet_balance: "উপলব্ধ ব্যালেন্স",
    wallet_deposit: "ডিপোজিট",
    wallet_withdraw: "উত্তোলন",
    wallet_history: "লেনদেনের ইতিহাস",
    wallet_amount: "পরিমাণ",
    wallet_method: "পদ্ধতি",
    wallet_tx_id: "ট্রানজেকশন আইডি",
    wallet_account: "অ্যাকাউন্ট নম্বর",
    wallet_submit: "জমা দিন",
    wallet_close: "বন্ধ করুন",
    wallet_all: "সকল",
    wallet_pending: "অপেক্ষমাণ",
    wallet_approved: "অনুমোদিত",
    wallet_rejected: "প্রত্যাখ্যাত",
    wallet_no_txs: "কোনো লেনদেন পাওয়া যায়নি।",
    wallet_total_deposit: "মোট ডিপোজিট",
    wallet_total_withdraw: "মোট উত্তোলন",
    wallet_entry_fees: "প্রবেশ মূল্য",
    wallet_prizes: "পুরস্কার জয়",

    // ── Common ───────────────────────────────────────────────────────────
    loading: "লোড হচ্ছে…",
    error: "ত্রুটি",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    close: "বন্ধ করুন",
    refresh: "রিফ্রেশ",
    retry: "পুনরায় চেষ্টা করুন",
    submit: "জমা দিন",
    by: "দ্বারা",
    free: "বিনামূল্যে",
    security_check: "নিরাপত্তা যাচাই",
    your_answer: "আপনার উত্তর",
  },
} satisfies Record<Lang, Record<string, string>>;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => translations.en[k],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try { return (localStorage.getItem("ff_lang") as Lang) ?? "en"; } catch { return "en"; }
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem("ff_lang", l); } catch {}
  };

  const t = (key: TranslationKey): string =>
    translations[lang][key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
