import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tournamentsRouter from "./tournaments";
import registrationsRouter from "./registrations";
import teamsRouter from "./teams";
import matchesRouter from "./matches";
import leaderboardRouter from "./leaderboard";
import announcementsRouter from "./announcements";
import usersRouter from "./users";
import adminRouter from "./admin";
import walletRouter from "./wallet";
import authRouter from "./auth";
import captchaRouter from "./captcha";
import notificationsRouter from "./notifications";
import referralsRouter from "./referrals";
import promoCodesRouter from "./promoCodes";
import rulesRouter from "./rules";
import settingsRouter from "./settings";
import supportRouter from "./support";
import userMatchesRouter from "./userMatches";

const router: IRouter = Router();

router.use(captchaRouter);
router.use(authRouter);
router.use(healthRouter);
router.use(tournamentsRouter);
router.use(registrationsRouter);
router.use(teamsRouter);
router.use(matchesRouter);
router.use(leaderboardRouter);
router.use(announcementsRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(walletRouter);
router.use(notificationsRouter);
router.use(referralsRouter);
router.use(promoCodesRouter);
router.use(rulesRouter);
router.use(settingsRouter);
router.use(supportRouter);
router.use(userMatchesRouter);

export default router;
